## Sahil Saini Salaria 
## Reg No : 180905048
## Roll No 11 C
## Lab3

In [6]:
import numpy as np

## Array creation

In [14]:
A=np.array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [11]:
A.dtype

dtype('int64')

In [12]:
B=np.array([1.3,2,3,4,5])
B

array([1.3, 2. , 3. , 4. , 5. ])

In [13]:
B.dtype

dtype('float64')

## Creating sequence of sequence will create 2-dimensional array.

In [18]:
A=np.array([[3,4,5],[1,2,3]])
z=np.zeros((2,4))


In [16]:
A

array([[3, 4, 5],
       [1, 2, 3]])

In [19]:
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Instead of step-size, we can specify total number of elements in the array using

In [21]:
S=np.linspace(0,2,9)
S

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

## usage of Random Number functions

In [22]:
import random

In [25]:
random.choice([1,2,3,4,5])

3

In [26]:
random.choice("Sahil")

'h'

In [27]:
random.randrange(2,10)

8

In [29]:
random.randrange(2,100,3)

83

In [30]:
random.random()

0.009318908043415286

In [32]:
random.uniform(2,10)

5.493144175984303

In [36]:
a=[1,2,3,4,5]
random.shuffle(a)

In [37]:
a

[2, 3, 4, 5, 1]

In [38]:
random.seed(10)

In [41]:
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [43]:
a.shape

(3, 5)

In [44]:
a.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [45]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

## Array operations

In [46]:
a=np.array([1,2,3,4,])
b=np.arange(4)

In [47]:
a

array([1, 2, 3, 4])

In [48]:
b

array([0, 1, 2, 3])

In [49]:
a-b

array([1, 1, 1, 1])

In [50]:
a**2

array([ 1,  4,  9, 16])

In [51]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [52]:
10*np.sin(a)

array([ 8.41470985,  9.09297427,  1.41120008, -7.56802495])

In [53]:
a<3

array([ True,  True, False, False])

## Matrix operations

In [54]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )

In [55]:
A*B

array([[2, 0],
       [0, 4]])

In [56]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [57]:
np.dot(A,B)

array([[5, 4],
       [3, 4]])

In [61]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
b.sum(axis=1) #Row

array([ 6, 22, 38])

In [64]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [65]:
b.sum()

66

## Indexing, Slicing & Iterating Array

In [66]:
a=np.arange(10)*3

In [67]:
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [68]:
a[2:5]

array([ 6,  9, 12])

In [69]:
a[1:6:2]

array([ 3,  9, 15])

In [70]:
b=np.arange(20).reshape(5,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [71]:
b[2,3]

11

In [73]:
for ele in b.flat:
    print(ele)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [74]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [76]:
b.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Stacking together different arrays

In [77]:
A1=np.arange(6).reshape(2,3)
A2=np.arange(6).reshape(2,3)

In [78]:
A1

array([[0, 1, 2],
       [3, 4, 5]])

In [79]:
A2

array([[0, 1, 2],
       [3, 4, 5]])

In [82]:
D1=np.vstack((A1,A2))
D1

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [85]:
D2=np.hstack((A1,A2))
D2

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [89]:
a=np.array([2,3])
b=np.array([4,5])
np.column_stack((a,b))

array([[2, 4],
       [3, 5]])

In [90]:
np.vstack((a,b))

array([[2, 3],
       [4, 5]])

## Indexing with array of indices

In [98]:
a=np.arange(20)
i=np.array([1,1,3,8,5])


In [99]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [101]:
a[i]

array([1, 1, 3, 8, 5])

In [102]:
j = np.array( [ [ 3, 4], [ 9, 7 ] ] )

In [103]:
a[j]

array([[3, 4],
       [9, 7]])

## Usage of for-loop (Mapping by Value)

In [104]:
a=np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [106]:
s1=0
for row in a:
    for col in row:
        s1=s1+col

s1

190

## Usage of for-loop (Mapping by Index)

In [107]:
a=np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [108]:
s1=0
for i in range(0,a.shape[0]):
    for j in range(0,a.shape[1]):
        s1=s1+a[i][j]
s1

190

## Ends