## Sahil Saini Salaria 
## Reg No : 180905048
## Roll No 11 C
## Lab3

## Q1 Write a program to find the factors of a given number (get input from user) using for loop.

In [1]:
def print_factors(x):
   print("The factors of",x,"are:")
   for i in range(1, x + 1):
       if x % i == 0:
           print(i)
            
num=int(input("Enter Number:"))
print_factors(num)


Enter Number:30
The factors of 30 are:
1
2
3
5
6
10
15
30


## Q2 Find the sum of columns and rows using axis

In [5]:
import numpy as np
a=np.arange(20).reshape(4,5)
print(a.sum(axis=1))
print(a.sum(axis=0))

[10 35 60 85]
[30 34 38 42 46]


## Q3     3. Operations on Arrays (use numpy wherever required):
    a) Create array from list with type float
    b) Create array from tuple
    c) Creating a 3X4 array with all zeros
    d) Create a sequence of integers  from 0 to 20 with steps of 5
    e)  Reshape 3X4 array to 2X2X3 array
    f) Find maximum and minimum element of array, Row wise max and min, column wise max and min and sum of elements. (Use functions max(), min(), sum())

In [ ]:
# a

In [9]:
a=np.array([1,2,3,4.0])
a.dtype

dtype('float64')

In [ ]:
# b

In [11]:
a=np.array((1,2,3,4.0))
a.dtype

dtype('float64')

In [ ]:
# c

In [13]:
np.zeros(12).reshape(3,4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# d

In [15]:
a=np.arange(0,20,5)
a

array([ 0,  5, 10, 15])

In [2]:
# e

In [19]:
a=np.arange(12).reshape(3,4).reshape(2,2,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [7]:
# f

In [6]:
a=np.arange(12).reshape(3,4)
a.sum(axis=0)

array([12, 15, 18, 21])

In [8]:
a.sum(axis=1)

array([ 6, 22, 38])

In [9]:
a.max(axis=0)

array([ 8,  9, 10, 11])

In [10]:
a.max(axis=1)

array([ 3,  7, 11])

In [11]:
a.min(axis=0)

array([0, 1, 2, 3])

In [12]:
a.min(axis=1)

array([0, 4, 8])

## Q4 Write a program to transpose a given matrix. 

In [30]:
a=np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
s1=0
for i in range(0,len(a)):
    for j in range(0,len(a[0])):
        if(i>j):
            temp=a[i][j]
            a[i][j]=a[j][i]
            a[j][i]=temp
a

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [36]:
#OR

In [34]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
a.T

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

## Q5 Write a program to add two matrices.

In [40]:
a=np.arange(25).reshape(5,5)
b=np.arange(25).reshape(5,5)
res=np.zeros(25).reshape(5,5)

for i in range(0,len(a)):
    for j in range(0,len(a[0])):
        res[i][j]=a[i][j]+b[i][j]
res

array([[ 0.,  2.,  4.,  6.,  8.],
       [10., 12., 14., 16., 18.],
       [20., 22., 24., 26., 28.],
       [30., 32., 34., 36., 38.],
       [40., 42., 44., 46., 48.]])

In [45]:
res=a+b
res

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

## Q6 Write a program to find element wise product between two matrices.

In [47]:
a=np.arange(25).reshape(5,5)
b=np.arange(25).reshape(5,5)
res=np.zeros(25).reshape(5,5)

for i in range(0,len(a)):
    for j in range(0,len(a[0])):
        res[i][j]=a[i][j]*b[i][j]
res

array([[  0.,   1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.,  81.],
       [100., 121., 144., 169., 196.],
       [225., 256., 289., 324., 361.],
       [400., 441., 484., 529., 576.]])

In [49]:
# OR

res=a*b
res

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

## ENDS